In [308]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [309]:
df= pd.read_csv("multiple-lr-data.csv")

In [310]:
#df.describe()

In [311]:
#finding x and y
# y=np.array(df['loan'])
# x1=np.array(df['age'])
# x2=np.array(df['credit-rating'])
# x3=np.array(df['children'])
a=np.array(df)
x1=a[:,0]
x2=a[:,1]
x3=a[:,2]
x=np.column_stack((x1,x2,x3))
y=a[:,3]

In [312]:
x.shape

(1338, 3)

In [313]:
x

array([[19.  , 27.9 ,  0.  ],
       [18.  , 42.13,  1.  ],
       [28.  , 33.  ,  3.  ],
       ...,
       [18.  , 36.85,  0.  ],
       [21.  , 25.8 ,  0.  ],
       [61.  , 29.07,  0.  ]])

In [314]:
#train and test split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, shuffle=False)
# x_train2, x_test2, y_train, y_test = train_test_split( x2, y, test_size=0.2, shuffle=False)
# x_train3, x_test3, y_train, y_test = train_test_split( x3, y, test_size=0.2, shuffle=False)

In [315]:
x_train

array([[19.   , 27.9  ,  0.   ],
       [18.   , 42.13 ,  1.   ],
       [28.   , 33.   ,  3.   ],
       ...,
       [39.   , 42.655,  0.   ],
       [63.   , 21.66 ,  1.   ],
       [54.   , 31.9  ,  1.   ]])

In [316]:
#transform of x for multiplication
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)

In [317]:
#h=t0+t1x1+t2x2+tnxn
#J is same as single var
#gradient is error X xj

In [318]:
#hyper parameters
alpha=0.0001
iterations=100000
t0=0.5
t1=0.5
t2=0.5
t3=0.5

In [319]:
#prediction function
def h(t0,t1,t2,t3):
    return t0+(t1*x_train[:,0])+(t2*x_train[:,1])+(t3*x_train[:,2])

In [320]:
#cost function
def get_cost(t0,t1,t2,t3):
    preds=h(t0,t1,t2,t3)  #error
    J=(preds-y_train)**2 #squaring
    J=J.mean()
    J=J/2 #gradient decsent looks good
    #print(J)
    return J

In [321]:
#testing preds
# def custom_plot(t0,t1,t2,t3):
#     preds=h(t0,t1,t2,t3)

In [322]:
#calculating gradients
def get_gradients(t0,t1,t2,t3):
    preds=h(t0,t1,t2,t3)
    g0=(preds-y_train).mean()
    g1=((preds-y_train)*x_train[:,0]).mean()  #each value multiplied in array
    g2=((preds-y_train)*x_train[:,1]).mean()
    g3=((preds-y_train)*x_train[:,2]).mean()
    return(g0,g1,g2,g3)

In [323]:
#update parameters
def update(t0,t1,t2,t3):
    (g0,g1,g2,g3)=get_gradients(t0,t1,t2,t3)
    t0=t0-alpha*g0 #g0 is slope
    t1=t1-alpha*g1
    t2=t2-alpha*g2
    t3=t3-alpha*g3
    return (t0,t1,t2,t3)

In [324]:
#fit the model/optimise
def fit(t0,t1,t2,t3):
    cost_progress=[]
    for i in range(iterations):
        t0,t1,t2,t3=update(t0,t1,t2,t3)
        cost=get_cost(t0,t1,t2,t3)
        cost_progress.append(cost)
    return (t0,t1,t2,t3,cost_progress)

In [325]:
(t0,t1,t2,t3,cost_progress)=fit(t0,t1,t2,t3)

In [326]:
def pred(t0,t1,t2,t3,x,y,z):
    return t0+t1*x+t2*y+t3*z

In [327]:
pred(t0,t1,t2,t3,x_test[:,0],x_test[:,1],x_test[:,2])

array([13936.10438332, 18454.77929343,  8814.72595329, 16663.54080675,
       15313.72602846, 11391.98658928, 15273.45975238,  7836.27617074,
       10495.05833571, 19990.35635343,  7101.56695429, 11063.33982021,
       10958.83776952, 11749.65914137, 18795.39423441, 12372.91724112,
       16162.81590136, 17100.50166832, 19364.37088687, 15104.05991381,
       15684.49579043, 16322.92586577, 10663.46628747,  8883.29392573,
       17398.63011808,  9640.86781536, 17116.06674314,  9514.37062758,
       15832.58201171, 10615.19874289, 10028.93453996, 16756.02561649,
       12456.86291589, 18179.35415308, 12201.10510884, 16358.28892287,
       14968.64824067, 15250.70917002, 10096.6968458 , 13381.68141234,
       16930.38424527, 15159.16247196, 15097.66236244, 10611.18097434,
        8008.99210772, 17228.34953515, 14953.83685342, 10865.20150529,
       12774.2053224 ,  9876.60711295,  9299.23497886, 16573.7916621 ,
       18302.81895694, 10773.86994614, 11798.26776776, 17262.84955833,
      

In [328]:
#cost function
def get_cost_t(t0,t1,t2,t3):
    preds=pred(t0,t1,t2,t3,x_test[:,0],x_test[:,1],x_test[:,2])  #error
    J=(preds-y_test)**2 #squaring
    J=J.mean()
    J=J/2 
    #print(J)#gradient decsent looks good
    return J

In [329]:
get_cost_t(t0,t1,t2,t3)

70631270.87861371